### ISSUE TITLE
Cannot use RPCServer. Maybe it is caused the 'Ajv' module was updated to version 8.15, which lacks the necessary compatibility.

### ISSUE THREAD

**Issue by Nextdrive-IanChiu** [mikuso/ocpp-rpc#77]
Hi

I'm using ocpp-rpc v2.0.1 with Node.js 18.12.0. I found that I cannot use this repo to create an RPCServer today.

Error message: 
```js
/app/node_modules/fast-uri/lib/schemes.js:102
  const nid = urnComponents.nid.toLowerCase()
                                ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Object.urnSerialize [as serialize] (/app/node_modules/fast-uri/lib/schemes.js:102:33)
    at Object.serialize (/app/node_modules/fast-uri/index.js:124:63)
    at _getFullPath (/app/node_modules/ocpp-rpc/node_modules/ajv/dist/compile/resolve.js:79:33)
    at getFullPath (/app/node_modules/ocpp-rpc/node_modules/ajv/dist/compile/resolve.js:75:12)
    at Ajv.getSchemaRefs (/app/node_modules/ocpp-rpc/node_modules/ajv/dist/compile/resolve.js:100:24)
    at Ajv._addSchema (/app/node_modules/ocpp-rpc/node_modules/ajv/dist/core.js:451:51)
    at Ajv.addSchema (/app/node_modules/ocpp-rpc/node_modules/ajv/dist/core.js:235:34)
    at Ajv.addSchema (/app/node_modules/ocpp-rpc/node_modules/ajv/dist/core.js:222:22)
    at createValidator (/app/node_modules/ocpp-rpc/lib/validator.js:60:9)
    at Object.<anonymous> (/app/node_modules/ocpp-rpc/lib/standard-validators.js:4:5)
```

After tracing the issue, maybe it is caused by https://github.com/ajv-validator/ajv/issues/2446.
Then I try to downgrade the `ajv` verison to v8.12.0 and it works fine!
Perhaps use the fixed version in package.json is a good one to prevent the compatibility issue from other npm modules.

**Comment by mikuso** [comment]
Thanks for the report.

I have now pinned the version of ajv at 8.14.0 until this issue can be resolved.

Fixed in 33f9d86472eca5028183bcd1afe061121d7f620d and published to npm as 2.1.2.
